### PR TITLE
Added support for ida9.0 beta

### PR DESCRIPTION
**Pull request by kanren3**
IDA 8.x does not support get_type_by_tid, and IDA 9.0 does not support ida_struct. I don't know of a way to support both simultaneously.

### CODE REVIEW

**Comment by QiuChenly** [comment]
File : core.py line 185, the api changed cause ida can not compare arm to "ARM".

latest 9.0, the arm be changed to "ARM". this patch fix arm64 machine ASM not work. 

```python
        arch_name = ida_ida.inf_get_procname()
        print(f"当前加载的CPU类型为: {arch_name}")

        if arch_name == "metapc":
            assembler = AsmX86()
        elif arch_name.startswith("arm") or arch_name.startswith("ARM"):
            assembler = AsmARM()```

**Comment by kanren3** [comment]
> File : core.py line 185, the api changed cause ida can not compare arm to "ARM".
> 
> latest 9.0, the arm be changed to "ARM". this patch fix arm64 machine ASM not work.
> 
> ```python
>         arch_name = ida_ida.inf_get_procname()
>         print(f"当前加载的CPU类型为: {arch_name}")
> 
>         if arch_name == "metapc":
>             assembler = AsmX86()
>         elif arch_name.startswith("arm") or arch_name.startswith("ARM"):
>             assembler = AsmARM()
> ```

Thank you, I didn't notice that.

**Comment by zhefox** [comment]
Traceback (most recent call last):
  File "C:\Program Files/IDA Professional 9.0/plugins\patching\core.py", line 128, in load
    self._init_assembler()
  File "C:\Program Files/IDA Professional 9.0/plugins\patching\core.py", line 175, in _init_assembler
    assembler = AsmARM()
TypeError: AsmARM.__init__() missing 1 required positional argument: 'inf'

**Comment by zhefox** [comment]
image
change line 665 in asm.py to if ida_ida.inf_is_be():

**Comment by kanren3** [comment]
> image change line 665 in asm.py to if ida_ida.inf_is_be():

Thank you for reminding me. In these two modifications, I replaced ida_struct and ida_typeinf with idc to ensure compatibility from version 7.6 to 9.0 beta.

**Comment by gaasedelen** [comment]
Thanks!

**Pull request merged**
